# This is a basic workflow to help you get started with Actions

name: "JFrog RPM Demo"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GENERIC_REPOSITORY: 'carlosmm-generic-local'
  DOWNLOAD_URL: 'https://releases.jfrog.io/artifactory'
  PATH: 'artifactory-pro-rpms/jfrog-artifactory-pro'
  FILE: 'jfrog-artifactory-pro-7.77.8.rpm'
  ARTIFACTORY_URL: 'soleng.jfrog.io'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: Ping server
        run: |
          # Ping the server
          jf rt ping
      - name: Download RPM package
        run: |
          # Download from JFrog Releases
          curl \
          -L \
          -O \
          ${{ env.DOWNLOAD_URL }}/${{ env.PATH }}/${{ env.FILE }}
      - name: Upload RPM package with checksum 
        run: |
          # Upload by checksum
          curl \
          -X PUT
          -H 'X-Checksum-Deploy: true' \
          -H 'X-Checksum-Sha1: sha1Value' \
          -H 'X-Checksum-Sha256: sha256Value' \
          -H 'X-Checksum: checksum value' \
          -H 'Authorization: Bearer ${{ secrets.JF_SOLENG_TOKEN }}' \
          https://${{ env.ARTIFACTORY_URL }}/artifactory/${{ env.GENERIC_REPOSITORY }}/${{ env.FILE }}
          -T ${{ env.FILE }}
